# Generated by Django 4.2.4 on 2023-09-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParishDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('prayer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.prayergroup')),
            ],
        ),
    ]
