# Generated by Django 4.2.4 on 2023-09-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_prayergroup_parishdirectory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishdirectory',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
