# Generated by Django 4.2.4 on 2023-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_parishdirectory_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('cover_poster', models.ImageField(blank=True, null=True, upload_to='event_covers')),
                ('detailed_poster', models.ImageField(upload_to='detailed_posters')),
            ],
        ),
    ]
