# Generated by Django 4.2.4 on 2023-09-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_poster',
            field=models.ImageField(default='img/about.jpg', upload_to='event_covers'),
        ),
    ]
