# Generated by Django 4.2.4 on 2023-09-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_answer_reply_question_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
