# Generated by Django 4.2.4 on 2023-09-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
