# Generated by Django 4.2.4 on 2023-09-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
