# Generated by Django 4.2.4 on 2023-09-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
