# Generated by Django 4.2.4 on 2023-09-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_registration_comments_registration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishdirectory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prayergroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
