# Generated by Django 4.2.4 on 2023-09-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_remove_parishdirectory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishdirectory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayergroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
