# Generated by Django 4.2.4 on 2023-09-18 05:26

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_parishdirectory_is_deleted_prayergroup_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayergroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
