# Generated by Django 4.2.4 on 2023-09-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_prayergroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayergroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
