# Generated by Django 4.2.4 on 2023-09-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_prayergroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayergroup',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='prayergroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='prayergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('name__exact', models.F('name'))), fields=('name',), name='unique_case_sensitive_name'),
        ),
    ]
