# Generated by Django 4.2.4 on 2023-09-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_remove_prayergroup_is_deleted_alter_prayergroup_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prayergroup',
            name='unique_case_sensitive_name',
        ),
        migrations.AddField(
            model_name='prayergroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prayergroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
