# Generated by Django 4.2.4 on 2023-09-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_remove_answer_report_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
