# Generated by Django 4.2.4 on 2023-09-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_reportanswer_reportuser_reportanswer_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportuser',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReportAnswer',
        ),
        migrations.DeleteModel(
            name='ReportUser',
        ),
    ]
