# Generated by Django 4.2.4 on 2023-09-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_delete_userquizattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quizquestionitem',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='QuizAnswerItem',
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='QuizQuestionItem',
        ),
    ]
