# Generated by Django 4.2.4 on 2023-10-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerResourcePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='resource_person_photos/')),
            ],
        ),
    ]
