# Generated by Django 4.2.4 on 2023-10-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_report_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='archive',
        ),
    ]
