# Generated by Django 4.2.4 on 2024-01-23 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_report_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_accounted_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_media_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MediaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.registration')),
            ],
        ),
        migrations.CreateModel(
            name='AccountedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.registration')),
            ],
        ),
    ]
