# Generated by Django 4.2.6 on 2024-03-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bill_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
