# Generated by Django 4.2.4 on 2024-04-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_transaction_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash_in_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
