# Generated by Django 4.2.4 on 2024-04-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_transaction_cash_in_hand'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
